# Generated by Django 2.1.1 on 2018-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20181004_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published_post',
            new_name='post',
        ),
    ]
